### YamlMime:ManagedReference
items:
- uid: CLib.FileSettings
  commentId: T:CLib.FileSettings
  id: FileSettings
  parent: CLib
  children:
  - CLib.FileSettings.Buffered
  - CLib.FileSettings.FileSizeLimitBytes
  - CLib.FileSettings.FlushToDiskInterval
  - CLib.FileSettings.LogFileName
  - CLib.FileSettings.LogFolder
  - CLib.FileSettings.OutputTemplate
  - CLib.FileSettings.RetentionDays
  langs:
  - csharp
  - vb
  name: FileSettings
  nameWithType: FileSettings
  fullName: CLib.FileSettings
  type: Class
  source:
    id: FileSettings
    path: D:\10_Project\CLib\CLib\Log\LogManager.cs
    startLine: 113
  assemblies:
  - CLib
  namespace: CLib
  syntax:
    content: public class FileSettings
    content.vb: Public Class FileSettings
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
- uid: CLib.FileSettings.LogFolder
  commentId: P:CLib.FileSettings.LogFolder
  id: LogFolder
  parent: CLib.FileSettings
  langs:
  - csharp
  - vb
  name: LogFolder
  nameWithType: FileSettings.LogFolder
  fullName: CLib.FileSettings.LogFolder
  type: Property
  source:
    id: LogFolder
    path: D:\10_Project\CLib\CLib\Log\LogManager.cs
    startLine: 115
  assemblies:
  - CLib
  namespace: CLib
  syntax:
    content: public string LogFolder { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property LogFolder As String
  overload: CLib.FileSettings.LogFolder*
- uid: CLib.FileSettings.LogFileName
  commentId: P:CLib.FileSettings.LogFileName
  id: LogFileName
  parent: CLib.FileSettings
  langs:
  - csharp
  - vb
  name: LogFileName
  nameWithType: FileSettings.LogFileName
  fullName: CLib.FileSettings.LogFileName
  type: Property
  source:
    id: LogFileName
    path: D:\10_Project\CLib\CLib\Log\LogManager.cs
    startLine: 118
  assemblies:
  - CLib
  namespace: CLib
  syntax:
    content: public string LogFileName { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property LogFileName As String
  overload: CLib.FileSettings.LogFileName*
- uid: CLib.FileSettings.RetentionDays
  commentId: P:CLib.FileSettings.RetentionDays
  id: RetentionDays
  parent: CLib.FileSettings
  langs:
  - csharp
  - vb
  name: RetentionDays
  nameWithType: FileSettings.RetentionDays
  fullName: CLib.FileSettings.RetentionDays
  type: Property
  source:
    id: RetentionDays
    path: D:\10_Project\CLib\CLib\Log\LogManager.cs
    startLine: 121
  assemblies:
  - CLib
  namespace: CLib
  syntax:
    content: public int RetentionDays { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property RetentionDays As Integer
  overload: CLib.FileSettings.RetentionDays*
- uid: CLib.FileSettings.FileSizeLimitBytes
  commentId: P:CLib.FileSettings.FileSizeLimitBytes
  id: FileSizeLimitBytes
  parent: CLib.FileSettings
  langs:
  - csharp
  - vb
  name: FileSizeLimitBytes
  nameWithType: FileSettings.FileSizeLimitBytes
  fullName: CLib.FileSettings.FileSizeLimitBytes
  type: Property
  source:
    id: FileSizeLimitBytes
    path: D:\10_Project\CLib\CLib\Log\LogManager.cs
    startLine: 124
  assemblies:
  - CLib
  namespace: CLib
  syntax:
    content: public long? FileSizeLimitBytes { get; set; }
    parameters: []
    return:
      type: System.Nullable{System.Int64}
    content.vb: Public Property FileSizeLimitBytes As Long?
  overload: CLib.FileSettings.FileSizeLimitBytes*
- uid: CLib.FileSettings.Buffered
  commentId: P:CLib.FileSettings.Buffered
  id: Buffered
  parent: CLib.FileSettings
  langs:
  - csharp
  - vb
  name: Buffered
  nameWithType: FileSettings.Buffered
  fullName: CLib.FileSettings.Buffered
  type: Property
  source:
    id: Buffered
    path: D:\10_Project\CLib\CLib\Log\LogManager.cs
    startLine: 127
  assemblies:
  - CLib
  namespace: CLib
  syntax:
    content: public bool Buffered { get; set; }
    parameters: []
    return:
      type: System.Boolean
    content.vb: Public Property Buffered As Boolean
  overload: CLib.FileSettings.Buffered*
- uid: CLib.FileSettings.FlushToDiskInterval
  commentId: P:CLib.FileSettings.FlushToDiskInterval
  id: FlushToDiskInterval
  parent: CLib.FileSettings
  langs:
  - csharp
  - vb
  name: FlushToDiskInterval
  nameWithType: FileSettings.FlushToDiskInterval
  fullName: CLib.FileSettings.FlushToDiskInterval
  type: Property
  source:
    id: FlushToDiskInterval
    path: D:\10_Project\CLib\CLib\Log\LogManager.cs
    startLine: 130
  assemblies:
  - CLib
  namespace: CLib
  syntax:
    content: public TimeSpan FlushToDiskInterval { get; set; }
    parameters: []
    return:
      type: System.TimeSpan
    content.vb: Public Property FlushToDiskInterval As TimeSpan
  overload: CLib.FileSettings.FlushToDiskInterval*
- uid: CLib.FileSettings.OutputTemplate
  commentId: P:CLib.FileSettings.OutputTemplate
  id: OutputTemplate
  parent: CLib.FileSettings
  langs:
  - csharp
  - vb
  name: OutputTemplate
  nameWithType: FileSettings.OutputTemplate
  fullName: CLib.FileSettings.OutputTemplate
  type: Property
  source:
    id: OutputTemplate
    path: D:\10_Project\CLib\CLib\Log\LogManager.cs
    startLine: 133
  assemblies:
  - CLib
  namespace: CLib
  syntax:
    content: public string OutputTemplate { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property OutputTemplate As String
  overload: CLib.FileSettings.OutputTemplate*
references:
- uid: CLib
  commentId: N:CLib
  href: CLib.html
  name: CLib
  nameWithType: CLib
  fullName: CLib
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object
  name: object
  nameWithType: object
  fullName: object
  nameWithType.vb: Object
  fullName.vb: Object
  name.vb: Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  name: Equals(object)
  nameWithType: object.Equals(object)
  fullName: object.Equals(object)
  nameWithType.vb: Object.Equals(Object)
  fullName.vb: Object.Equals(Object)
  name.vb: Equals(Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  name: Equals(object, object)
  nameWithType: object.Equals(object, object)
  fullName: object.Equals(object, object)
  nameWithType.vb: Object.Equals(Object, Object)
  fullName.vb: Object.Equals(Object, Object)
  name.vb: Equals(Object, Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.equals#system-object-equals(system-object-system-object)
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  name: GetHashCode()
  nameWithType: object.GetHashCode()
  fullName: object.GetHashCode()
  nameWithType.vb: Object.GetHashCode()
  fullName.vb: Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gethashcode
  - name: (
  - name: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  name: GetType()
  nameWithType: object.GetType()
  fullName: object.GetType()
  nameWithType.vb: Object.GetType()
  fullName.vb: Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.gettype
  - name: (
  - name: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  name: MemberwiseClone()
  nameWithType: object.MemberwiseClone()
  fullName: object.MemberwiseClone()
  nameWithType.vb: Object.MemberwiseClone()
  fullName.vb: Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.memberwiseclone
  - name: (
  - name: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  name: ReferenceEquals(object, object)
  nameWithType: object.ReferenceEquals(object, object)
  fullName: object.ReferenceEquals(object, object)
  nameWithType.vb: Object.ReferenceEquals(Object, Object)
  fullName.vb: Object.ReferenceEquals(Object, Object)
  name.vb: ReferenceEquals(Object, Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.referenceequals
  - name: (
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: ','
  - name: " "
  - uid: System.Object
    name: Object
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object
  - name: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  name: ToString()
  nameWithType: object.ToString()
  fullName: object.ToString()
  nameWithType.vb: Object.ToString()
  fullName.vb: Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.object.tostring
  - name: (
  - name: )
- uid: System
  commentId: N:System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system
  name: System
  nameWithType: System
  fullName: System
- uid: CLib.FileSettings.LogFolder*
  commentId: Overload:CLib.FileSettings.LogFolder
  href: CLib.FileSettings.html#CLib_FileSettings_LogFolder
  name: LogFolder
  nameWithType: FileSettings.LogFolder
  fullName: CLib.FileSettings.LogFolder
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.string
  name: string
  nameWithType: string
  fullName: string
  nameWithType.vb: String
  fullName.vb: String
  name.vb: String
- uid: CLib.FileSettings.LogFileName*
  commentId: Overload:CLib.FileSettings.LogFileName
  href: CLib.FileSettings.html#CLib_FileSettings_LogFileName
  name: LogFileName
  nameWithType: FileSettings.LogFileName
  fullName: CLib.FileSettings.LogFileName
- uid: CLib.FileSettings.RetentionDays*
  commentId: Overload:CLib.FileSettings.RetentionDays
  href: CLib.FileSettings.html#CLib_FileSettings_RetentionDays
  name: RetentionDays
  nameWithType: FileSettings.RetentionDays
  fullName: CLib.FileSettings.RetentionDays
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.int32
  name: int
  nameWithType: int
  fullName: int
  nameWithType.vb: Integer
  fullName.vb: Integer
  name.vb: Integer
- uid: CLib.FileSettings.FileSizeLimitBytes*
  commentId: Overload:CLib.FileSettings.FileSizeLimitBytes
  href: CLib.FileSettings.html#CLib_FileSettings_FileSizeLimitBytes
  name: FileSizeLimitBytes
  nameWithType: FileSettings.FileSizeLimitBytes
  fullName: CLib.FileSettings.FileSizeLimitBytes
- uid: System.Nullable{System.Int64}
  commentId: T:System.Nullable{System.Int64}
  parent: System
  definition: System.Nullable`1
  href: https://learn.microsoft.com/dotnet/api/system.int64
  name: long?
  nameWithType: long?
  fullName: long?
  nameWithType.vb: Long?
  fullName.vb: Long?
  name.vb: Long?
  spec.csharp:
  - uid: System.Int64
    name: long
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int64
  - name: '?'
  spec.vb:
  - uid: System.Int64
    name: Long
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.int64
  - name: '?'
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: <
  - name: T
  - name: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    isExternal: true
    href: https://learn.microsoft.com/dotnet/api/system.nullable-1
  - name: (
  - name: Of
  - name: " "
  - name: T
  - name: )
- uid: CLib.FileSettings.Buffered*
  commentId: Overload:CLib.FileSettings.Buffered
  href: CLib.FileSettings.html#CLib_FileSettings_Buffered
  name: Buffered
  nameWithType: FileSettings.Buffered
  fullName: CLib.FileSettings.Buffered
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.boolean
  name: bool
  nameWithType: bool
  fullName: bool
  nameWithType.vb: Boolean
  fullName.vb: Boolean
  name.vb: Boolean
- uid: CLib.FileSettings.FlushToDiskInterval*
  commentId: Overload:CLib.FileSettings.FlushToDiskInterval
  href: CLib.FileSettings.html#CLib_FileSettings_FlushToDiskInterval
  name: FlushToDiskInterval
  nameWithType: FileSettings.FlushToDiskInterval
  fullName: CLib.FileSettings.FlushToDiskInterval
- uid: System.TimeSpan
  commentId: T:System.TimeSpan
  parent: System
  isExternal: true
  href: https://learn.microsoft.com/dotnet/api/system.timespan
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: CLib.FileSettings.OutputTemplate*
  commentId: Overload:CLib.FileSettings.OutputTemplate
  href: CLib.FileSettings.html#CLib_FileSettings_OutputTemplate
  name: OutputTemplate
  nameWithType: FileSettings.OutputTemplate
  fullName: CLib.FileSettings.OutputTemplate
